Adding more checks..

diff --git a/kubernetes/cmsweb/crons/cron-cric.yaml b/kubernetes/cmsweb/crons/cron-cric.yaml
--- a/kubernetes/cmsweb/crons/cron-cric.yaml
+++ b/kubernetes/cmsweb/crons/cron-cric.yaml
@@ -1,4 +1,34 @@
 apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: cric-fetch-script
+  namespace: auth
+data:
+  fetch-cric.sh: |
+    #!/bin/sh
+    echo "Starting CRIC fetch script..."
+    odir=/etc/cric/cric.json
+    tstamp=`date "+%Y%m%d_%H%M%S"`
+    response_code=$(curl --cert /etc/robots/robotcert.pem --key /etc/robots/robotkey.pem \
+        -k -L -s -w "%{response_code}" \
+        "https://cms-cric.cern.ch/api/accounts/user/query/?json&preset=roles123" -o ${odir}.${tstamp})
+    echo "Curl command executed with response code: $response_code"
+
+    if [ "$?" == "0" ] && [ "$response_code" == "200" ]; then
+        mv ${odir}.${tstamp} ${odir}
+        echo "CRIC data fetched successfully and moved to ${odir}."
+    else
+        echo "Failed to fetch CRIC data or invalid response code: $response_code"
+    fi
+
+    echo "=== Head of ${odir} ==="
+    head -n 10 ${odir}
+
+    echo "=== Tail of ${odir} ==="
+    tail -n 10 ${odir}
+    echo "Script completed."
+---
+apiVersion: v1
 kind: PersistentVolume
 metadata:
   name: cric-pv
@@ -39,17 +69,15 @@ spec:
             fsGroup: 0
           containers:
           - name: cric-fetch
-            image: registry.cern.ch/cmsweb/curl:latest-stable
-            args:
-            - /bin/sh
-            - -c
-            - >
-              curl --cert /etc/robots/robotcert.pem --key /etc/robots/robotkey.pem -k -L -s "https://cms-cric.cern.ch/api/accounts/user/query/?json&preset=roles" -o /etc/cric/cric.json
+            image: curlimages/curl:latest
+            command: ["/bin/sh", "/script/fetch-cric.sh"]
             volumeMounts:
             - name: cric-volume
               mountPath: /etc/cric
             - name: robot-secrets
               mountPath: /etc/robots
+            - name: script-volume
+              mountPath: "/script"
           restartPolicy: Never
           volumes:
           - name: cric-volume
@@ -58,3 +86,7 @@ spec:
           - name: robot-secrets
             secret:
               secretName: robot-secrets
+          - name: script-volume
+            configMap:
+              name: cric-fetch-script
+              defaultMode: 0777
