Swap MYSQL_ with MDB_ environment variables

diff --git a/docker/pypi/wmagent/bin/manage b/docker/pypi/wmagent/bin/manage
--- a/docker/pypi/wmagent/bin/manage
+++ b/docker/pypi/wmagent/bin/manage
@@ -85,7 +85,7 @@ db_prompt(){
     case $AGENT_FLAVOR in
         'mysql')
             # _exec_mysql $@
-            mysql -u $MYSQL_USER --password=$MYSQL_PASS -h $MYSQL_HOST --database=$wmaDBName --pager='less -SFX'
+            mysql -u $MDB_USER --password=$MDB_PASS -h $MDB_HOST --database=$wmaDBName --pager='less -SFX'
             ;;
         'oracle')
             _exec_oracle $@
@@ -110,7 +110,7 @@ init_wmagent(){
         'mysql')
             _exec_mysql "create database if not exists $wmaDBName" && \
                 echo "$FUNCNAME: MYSQL database: $wmaDBName has been created"
-            local database_options="--mysql_url=mysql://$MYSQL_USER:$MYSQL_PASS@$MYSQL_HOST/$wmaDBName "
+            local database_options="--mysql_url=mysql://$MDB_USER:$MDB_PASS@$MDB_HOST/$wmaDBName "
             ;;
         'oracle')
             echo "$FUNCNAME: Using ORACLE user schema: $ORACLE_USER@$ORACLE_TNS "
@@ -230,17 +230,17 @@ clean_agent(){
 # Wipe out MySQL and Oracle databases
 # Will cause next start to recreate databases
 clean_mysql(){
-    [[ -z $MYSQL_USER ]] && { echo "$FUNCNAME: ERROR: Not using MySQL..."; exit 1 ; }
+    [[ -z $MDB_USER ]] && { echo "$FUNCNAME: ERROR: Not using MySQL..."; exit 1 ; }
     local errVal=0
     echo
-    echo    "$FUNCNAME: THE CURRENT OPERATIONS WILL WIPE OUT THE $WMA_DATABASE DATABASE."
+    echo    "$FUNCNAME: THE CURRENT OPERATIONS WILL WIPE OUT THE $wmaDBName DATABASE."
     echo -n "$FUNCNAME: Continue? [n]: "
     read x && [[ $x =~ (y|yes|yeS|yEs|Yes|yES|YEs|YeS|YES|Y) ]] || return 102
     echo "$FUNCNAME: ..."
     echo "$FUNCNAME: You still have 5 sec. to cancel before we proceed."
     echo
     sleep 5
-    echo "$FUNCNAME: Dropping MySQL DB... ";
+    echo "$FUNCNAME: Dropping MariaDB DB... ";
     _exec_mysql "drop database $wmaDBName"   || let errVal+=$?
     [[ $errVal -eq 0 ]] &&  rm -f $wmaInitSqlDB
     return $errVal
@@ -250,7 +250,7 @@ clean_oracle(){
     [[ -z $ORACLE_USER ]] && { echo "$FUNCNAME: ERROR: Not using ORACLE..."; exit 1 ; }
     local errVal=0
     echo
-    echo    "$FUNCNAME: THE CURRENT OPERATIONS WILL WIPE OUT THE $WMA_DATABASE DATABASE."
+    echo    "$FUNCNAME: THE CURRENT OPERATIONS WILL WIPE OUT THE $wmaDBName DATABASE."
     echo -n "$FUNCNAME: Continue? [n]: "
     read x && [[ $x =~ (y|yes|yeS|yEs|Yes|yES|YEs|YeS|YES|Y) ]] || return 102
     echo "$FUNCNAME: ..."
